# Generated by Django 4.2.19 on 2025-03-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('Resume', models.CharField(max_length=150)),
                ('auteur', models.CharField(blank=True, max_length=150, null=True)),
                ('Contenu', models.CharField(max_length=150)),
                ('Date_de_mise_a_jour', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
