# Generated by Django 4.2.19 on 2025-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='prix',
            field=models.FloatField(),
        ),
    ]
