# Generated by Django 5.1.6 on 2025-03-21 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_commande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='articles',
        ),
        migrations.AddField(
            model_name='panier',
            name='article',
            field=models.ManyToManyField(to='articles.articles'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
